import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import useSWR from 'swr'
import { WasherStatus } from './api/washer'

const inter = Inter({ subsets: ['latin'] })

const WASHERS = [
  1486,
  1485,
  1484,
  1483,
  1482,
  1481,
  1480,
  1479,
]

const WASHER_STATUS_TEXT = [
  '',
  '空闲中',
  '使用中',
  '预约中',
  '离线',
  '未激活',
  '不存在',
  '锁定中'
]

const WasherCard = ({ wid }: {wid: string}) => {
  const { data, error } = useSWR<WasherStatus>(`/api/washer?id=${wid}`, (url: string) => fetch(url).then((r) => r.json()))
  if (error) return <div>failed to load</div>
  if (!data) return <div>loading...</div>
  return (
    <div className={styles.card}>
      <h2 className={inter.className}>{data.name}</h2>
      <p className={inter.className}>{WASHER_STATUS_TEXT[data.status]}</p>
      <p className={inter.className}>{data.ddl}</p>
      <p className={inter.className}>{data.message}</p>
    </div>
  )
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {WASHERS.map((wid) => (<WasherCard wid={wid.toString()} />))}
      </main>
    </>
  )
}
