import Head from 'next/head'
import { Inter } from '@next/font/google'
import useSWR from 'swr'
import { WasherStatus } from './api/washer'

const inter = Inter({ subsets: ['latin'] })

const WASHERS = [
  1486,
  1485,
  1484,
  1483,
  1482,
  1481,
  1480,
  1479,
]

const WASHER_STATUS_TEXT = [
  '',
  '空闲中',
  '使用中',
  '预约中',
  '离线',
  '未激活',
  '不存在',
  '锁定中',
  '获取中',
]

const WasherCard = ({ wid }: { wid: string }) => {
  const { data, error } = useSWR<WasherStatus>(`/api/washer?id=${wid}`, (url: string) => fetch(url).then((r) => r.json()))
  if (error) return <div>failed to load</div>
  return (
    <div className='bg-light-300 border-b-4 h-44 p-4 bg-gray-300 m-1 rounded transition-all duration-150 hover:shadow-lg hover:opacity-80'>
      <h2 className='text-2xl font-bold py-2'>{data?.name ?? '获取中'}</h2>
      {
        !data ?
          <p className='text-base font-bold text-gray-500'>{'获取中'}</p>
          : data!.status === 1 ?
            <p className='text-base font-bold text-amber-500'>{WASHER_STATUS_TEXT[data.status!!]}</p>
            : <p className='text-base font-bold text-gray-500'>{WASHER_STATUS_TEXT[data.status!!]}</p>
      }
      {data?.ddl && (
        <div className='my-2 text-gray-900/90 primary-text font-mono text-xs'>
          <span>DDL:{' '}</span>
          <span className='font-semibold'>{data!.ddl}</span>
        </div>
      )
      }

    </div>
  )
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Laundry Monitor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className=' '>
          <h1 className='text-center text-3xl'>橘4B洗衣房裁判席</h1>
          <div className='grid place-content-center gap-4 grid-cols-1 sm:grid-cols-2 md:grid-cols-4'>
            {WASHERS.map((wid) => (<WasherCard wid={wid.toString()} key={wid} />))}
          </div>
        </div>

      </main>
    </>
  )
}
